### PR TITLE
photutils v0.7.1

### PR DESCRIPTION
**Pull request by larrybradley**
Update photutils to `v0.7.1`.  The PR is to the `v0.7.x` branch.

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by larrybradley** [comment]
@conda-forge-admin, please rerender

**Comment by bsipocz** [comment]
@larrybradley - weird that the bot didn't picked up this release automatically. How long did you wait between pushing to pypi and opening this?

**Comment by larrybradley** [comment]
I waited probably an hour or so before remembering (although I could be wrong) that the bot doesn't pick up bug fix releases (i.e. tags on a bugfix branch instead of master).  So I created a `0.7.x` branch in this repo and then submit a PR for 0.7.1 against that branch.  That's what I did in the past for 0.4.x.

**Comment by bsipocz** [comment]
it should pick up everything that comes up at the top of the list on pypi. (e.g. it picked up astropy 3.2.2, but not 2.0.15 as the latter was never the "latest" in semver).

Maybe worth a ping to @conda-forge/core?

**Comment by bsipocz** [comment]
OK, my confusion is cleared. The bot did work, but was just much slower (see #13), and now I realized that you meant the 0.7.x branch here, not in photutils. I think it's unnecessary, unless there are plans to do parallel releases like we do in astropy with LTS *and* bugfix at the same time.

**Comment by larrybradley** [comment]
Ah, OK!  Yes, the bot is usually quite fast.

**Comment by CJ-Wright** [comment]
The bot has been having some issues recently. Hopefully should be fixed soon.

**Pull request merged**
