### PR TITLE
Manual rebuild for py311 with c-f migrator

### PR DESCRIPTION
**Pull request by jochym**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jochym** [comment]
@conda-forge-admin, please rerender

**Comment by jochym** [comment]
@larrybradley : me again. I think the bot has currently some problems picking up this feedstock for retrying rebuild again. So I did the job manually (put the migrator conf into .ci_suport and re-rendered - exactly what the bot would do). The error on travis is due to some problem between github and travis (the clone failed). I cannot trigger rebuild without triggering everything. Maybe you can.

**Comment by larrybradley** [comment]
Many thanks, @jochym. The travis job failed again. Meanwhile, the bot submitted a separate PR for py311 that passed.  I'll merge that PR and close this PR.  Thanks again!

**Comment by jochym** [comment]
Great. I must have missed something there. Glad the bot got to it finally.

**Pull request closed without merging**
