### PR TITLE
Add python 3.7 builds

### PR DESCRIPTION
**Pull request by larrybradley**

### CODE REVIEW

**Comment by larrybradley** [comment]
It looks like Python 3.7 builds are not yet available for linux and windows. 🙁

**Comment by bsipocz** [comment]
@larrybradley - as far as I understood they are working on a huge backlog (they are changing the compiler, adding py37 support and also bumping the R version for the R packages). So even our upstream packages are missing. The status can be followed here, ETA was said to be a few months 😞  https://conda-forge.org/status/

**Comment by larrybradley** [comment]
@bsipocz Thanks for the update!  I was hoping it would be ready by now. ☹️

**Comment by bsipocz** [comment]
Yes. Apparently conda-forge is huge now, but with it still has to work with the default CI resources. Hopefully there'll be a solution for that sometimes soon, so I expect upgrading to py3.8 will be a much smoother ride.

**Comment by bsipocz** [comment]
@larrybradley - I'm closing this. Now that the upgrade for the astropy core package has been done, the bot should get to photutils fairly soon with a new PR.

**Pull request closed without merging**
